version: "3"

services:
  test:
    build:
      context: .
    working_dir: /elliptic
    command: >
      sh -c "python -m unittest && flake8"
    volumes:
      - ./:/elliptic
  benchmarks:
    build:
      context: .
    image: padmec/pymoab-pytrilinos:3.6
    working_dir: /elliptic
    command: python run.py
    volumes:
    - ./:/elliptic
